# @package _global_

algorithm:
  _target_: dqn.train.main
  name: "dqn"
  model:
    _target_: dqn.model.QNetwork
    layers:
      - 128
      - 128
    critic:
      parameter_sharing: False # True/False/List[int] (seps_indices)

    device : "cpu"  # a pytorch device ("cpu" or "cuda")

  training_start : 2000
  buffer_size : 10000

  optimizer : "Adam"
  lr : 1.e-4
  optim_eps : 0.00001
  gamma : 0.99
  batch_size : 512

  grad_clip : null

  use_proper_termination : True  # True/False/'ignore'
  standarize_returns: True

  eps_start : 1.0
  eps_end : 0.05
  eps_decay : 6.5
  greedy_epsilon : 0.05

  target_update_interval_or_tau: 200

